### ISSUE TITLE
build on phonegap error on phonegap-version 6.1.0

### ISSUE THREAD

**Issue by calebeaires** [brody2consult/cordova-sqlite-ext#28]
```
Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-sqlite-ext" via npm Installing "cordova-sqlite-ext" at "0.10.0" for android Failed to install 'cordova-sqlite-ext':CordovaError: Uh oh! 
"/tmp/gimlet/23886140/2058005/www_android/project/cordova/plugins/cordova-sqlite-ext/node_modules/cordova-sqlite-ext-deps/libs/sqlite-connector.jar" not found! at copyFile (/tmp/gimlet/23886140/2058005/www_android/project/cordova/lib/pluginHandlers.js:182:36) at copyNewFile (/tmp/gimlet/23886140/2058005/www_android/project/cordova/lib/pluginHandlers.js:214:5) at handlers.source-file.install 
(/tmp/gimlet/23886140/2058005/www_android/project/cordova/lib/pluginHandlers.js:34:13) at Object.ActionStack.process 
(/tmp/gimlet/23886140/2058005/www_android/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25) at Api.addPlugin (/tmp/gimlet/23886140/2058005/www_android/project/cordova/Api.js:205:20) 
at handleInstall (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:602:6) at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:391:24 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13) Uh oh! 
"/tmp/gimlet/23886140/2058005/www_android/project/cordova/plugins/cordova-sqlite-ext/node_modules/cordova-sqlite-ext-deps/libs/sqlite-connector.jar" not found! - You can fix this here
```

This is the bug report:

The most likely cause for this error is error is that you have included plugin javascript files in your app package, such as barcodescanner.js, GAPlugin.js, cdv-plugin-fb-connect.js, or any other plugin files such as the childbrowser assets directory.

Previously we used pluginstall to install plugins, which would simply overwrite files in your app. However we recently migrated to plugman, which will not overwrite these files and instead fails.

**Comment by winstef** [comment]
Same issue with Phonegap build, sticking to 0.8.0 seems to be working for me.

**Comment by brody2consult** [comment]
This is because plugman, PhoneGap CLI, and PhoneGap Build do not honor the `before_plugin_install` hook. This is also an issue with Intel XDK. A new version at https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free supports these tools and is available under GPL and commercial license options. For a commercial license please contact: sales@litehelpers.net
