### ISSUE TITLE
Failed added plugin to cordova-android@8.0.0

### ISSUE THREAD

**Issue by frontenddeveloping** [brody2consult/cordova-sqlite-ext#84]
I run `cordova platform add android@8.0.0 --verbose`
```
Failed to install 'cordova-sqlite-ext': CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/Users/Pinal/.nvm/versions/node/v10.15.3/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/Pinal/other/repair360/ReconPro-vNext/plugins/cordova-sqlite-ext/scripts/beforePluginInstall.js:13:21)
    at runScriptViaModuleLoader (/Users/Pinal/.nvm/versions/node/v10.15.3/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/Users/Pinal/.nvm/versions/node/v10.15.3/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /Users/Pinal/.nvm/versions/node/v10.15.3/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
```

I'm tried to update my project from Cordova 8 to 9 version

**Comment by AhmadAyyaz1993** [comment]
I am getting the same error with cordova platform add android@8.0.0. Did you find a solution for this?

**Comment by frontenddeveloping** [comment]
@aarononeal , I'm still using 2.2 version of cordova-sqlite-ext instead of 3.0, this error appeared after update to 3.0 version of this plugin

**Comment by frontenddeveloping** [comment]
The root of this problem is using `requireCordovaModule` in hooks of this plugin, now it should be changed to `require` function

**Comment by brody2consult** [comment]
This issue was already fixed in the most recent plugin version. I **highly** recommend you guys do the following:

- completely remove `plugins` and `platforms` directories
- ensure that these 2 directories are in `.gitignore` file, as they should not be committed
- use Cordova tooling to install latest plugin versions
- use Cordova tooling to install recent Cordova platform versions

In case the issue persists, please give <https://github.com/brodybits/cordova-sqlite-ext-bootstrap-starter-app> a try.

In case the issue continues to persist with updated plugin, please make & post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
