### ISSUE TITLE
Getting error while building after adding cordova-android@8.0.0

### ISSUE THREAD

**Issue by AhmadAyyaz1993** [brody2consult/cordova-sqlite-ext#85]
Installing "cordova-sqlite-ext" for android
Failed to install 'cordova-sqlite-ext': CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (D:\TMS-GIT\com.tracer.joblogic\node_modules\cordova\node_modules\cordova-lib\src\hooks\Context.js:57:15)
    at module.exports (D:\TMS-GIT\com.tracer.joblogic\plugins\cordova-sqlite-ext\scripts\beforePluginInstall.js:13:21)
    at runScriptViaModuleLoader (D:\TMS-GIT\com.tracer.joblogic\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:181:32)
    at runScript (D:\TMS-GIT\com.tracer.joblogic\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:16)
    at D:\TMS-GIT\com.tracer.joblogic\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:125:20
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by brody2consult** [comment]
The new 3.0.0 version should not have this kind of an issue.
