### ISSUE TITLE
Google API Level 33 support

### ISSUE THREAD

**Issue by itsonit** [brody2consult/cordova-sqlite-ext#96]
I'am not able to open database with an spp based on a API Level 33 build. In the past, API Level 32 and above i got no problems.

Anyone able to build a working app based in API Level 33?

**Comment by mreis1** [comment]
@itsonit Google forced us to target the API Level 33 before August 31 which I did and after some tests everything seemed to be working fine. Can you provide additional information on your build errors? Which cordova-android and cordova-cli version are using? 

Although targeting API Level 33 came with an exponential instability as the image below demonstrastes.

<img width="1617" alt="image" src="https://github.com/brodybits/cordova-sqlite-ext/assets/1719667/589877c7-9f22-4681-a3dd-77e9102c1947">

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlc-ndk-native-driver.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1661)
       at io.liteglue.SQLiteConnector.<init>(SQLiteConnector.java:8)
       at io.sqlc.SQLiteConnectorDatabase.<clinit>(SQLiteConnectorDatabase.java:35)
       at io.sqlc.SQLitePlugin.openDatabase(SQLitePlugin.java:219)
       at io.sqlc.SQLitePlugin.access$000(SQLitePlugin.java:33)
       at io.sqlc.SQLitePlugin$DBRunner.run(SQLitePlugin.java:391)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
       ```
