### ISSUE TITLE
Google API Level 35 support + Page size 16K

### ISSUE THREAD

**Issue by hooliapps** [brody2consult/cordova-sqlite-ext#99]
Hello

It seems that this plugin will not be compatible (breaking change) with Google API Level 35 support + Page size 16K.

Possible to check please ?
https://developer.android.com/guide/practices/page-sizes
https://developer.android.com/about/versions/15

* Seems the libraries .so and/or Jar must be recompilated

**Comment by hooliapps** [comment]
Hello, tested with Pixel 8 With Android 15 QR1 + Page Size 16Kb Mode.

App don't works and are not downloadable from Google Play also.

**Comment by hooliapps** [comment]
Hello

For info, I did a similar correction on these repos (recompilation to do):
- https://github.com/brodycj/cordova-sqlite-ext-deps/pull/3
- https://github.com/brodycj/Android-sqlite-ext-native-driver/pull/2

+ In your Cordova app, you must add the following code in /app/build.gradle, under android { block:
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }

**Comment by oudoken** [comment]
Hi there,

@brody4hire 

Maybe i'm wrong but it will suffice to update this project file "package.json" adding the correct dependencies:
`"dependencies": {
    "cordova-sqlite-storage-dependencies": "5.0.0"
  }`

Thanks kind regards,
Roberto

**Comment by oudoken** [comment]
Hi @brody4hire,
Please can You update also this repo like the main "https://github.com/storesafe/cordova-sqlite-storage"???
Thanks Kind Regards
Rob

**Comment by ancipov** [comment]
It looks like company https://appery.io made a branch of this plugin https://github.com/appery-io/cordova-sqlite-ext with fix Google API Level 35 support + Page size 16K

**Comment by ancipov** [comment]
> * ordova app, you must add the following code in /app/build.gradle, under android { block:
>   packagingOptions {
>   jniLibs {
>   useLegacyPackaging = true

I build apk file with your fix but got the following error when run the app

java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlc-ndk-native-driver.so" not found
at java.lang.Runtime.loadLibrary0(Runtime.java:1090)
at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
at java.lang.System.loadLibrary(System.java:1765)

**Comment by brody2consult** [comment]
Adding link to cordova-sqlite-storage issue: https://github.com/storesafe/cordova-sqlite-storage/issues/1021

**Comment by brody2consult** [comment]
Now resolved with recent cordova-sqlite-ext `7.0.0` update; used check_elf_alignment.sh script to check APK build of `spec` with this update ref: https://developer.android.com/guide/practices/page-sizes#alignment-use-script

**Comment by KevinKelchen** [comment]
Thank you so much for this, Chris! ❤️

**Comment by oudoken** [comment]
@brody4hire 
Thanks forte update!
